// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6qt3Qdz9ahLQAeaK0tAJCJgiFfSZegw8',
    appId: '1:78302766121:web:a6b32166a815aefe57a838',
    messagingSenderId: '78302766121',
    projectId: 'bbquiz-f473b',
    authDomain: 'bbquiz-f473b.firebaseapp.com',
    storageBucket: 'bbquiz-f473b.firebasestorage.app',
    measurementId: 'G-QD1RMS5R6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hRu6atZ5lFfj0poys4ancCmGYrUo6uU',
    appId: '1:78302766121:android:475dfe2483e4cae257a838',
    messagingSenderId: '78302766121',
    projectId: 'bbquiz-f473b',
    storageBucket: 'bbquiz-f473b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWMblVIL6VMr1IPe4bHESKqIlv_qkeeA',
    appId: '1:78302766121:ios:eef407f4c503ae4357a838',
    messagingSenderId: '78302766121',
    projectId: 'bbquiz-f473b',
    storageBucket: 'bbquiz-f473b.firebasestorage.app',
    iosBundleId: 'com.example.bbquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWMblVIL6VMr1IPe4bHESKqIlv_qkeeA',
    appId: '1:78302766121:ios:eef407f4c503ae4357a838',
    messagingSenderId: '78302766121',
    projectId: 'bbquiz-f473b',
    storageBucket: 'bbquiz-f473b.firebasestorage.app',
    iosBundleId: 'com.example.bbquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6qt3Qdz9ahLQAeaK0tAJCJgiFfSZegw8',
    appId: '1:78302766121:web:a9bbfd012586be7f57a838',
    messagingSenderId: '78302766121',
    projectId: 'bbquiz-f473b',
    authDomain: 'bbquiz-f473b.firebaseapp.com',
    storageBucket: 'bbquiz-f473b.firebasestorage.app',
    measurementId: 'G-N9YHE4QJB5',
  );
}
